### ISSUE TITLE
@arcgis/core: 

### ISSUE THREAD

**Issue by brian32768** [Esri/feedback-js-api-next#75]
**Describe the bug**
Sample app won't run with Parcel bundler. The error message is 

`×  C:\Users\bwilson\source\repos\arcgis-js-api-test\node_modules\@arcgis\core\views\2d\engine\webgl\mesh\bufcut.js: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got "VariableDeclaration"
`
**Framework and build tools** 
I'm using Windows 10 and parcel. 

**To Reproduce**
Attached file contains source files including package.json, index.html, index.js
`npm install
npm start
`
[arcgis_js_api_test.zip](https://github.com/Esri/feedback-js-api-next/files/5357639/arcgis_js_api_test.zip)

**Expected behavior**
The parcel server will start the server at localhost:1234 but it will give the following output and then won't run in the browser.
` parcel serve index.html

Server running at http://localhost:1234
\ Building index.js...Browserslist: caniuse-lite is outdated. Please run next command `npm update`
- Building bundle-loader.js...Browserslist: caniuse-lite is outdated. Please run next command `npm update`
/ Building cast.js...Browserslist: caniuse-lite is outdated. Please run next command `npm update`
**×  C:\Users\bwilson\source\repos\arcgis-js-api-test\node_modules\@arcgis\core\views\2d\engine\webgl\mesh\bufcut.js: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got "VariableDeclaration"
**
    at Object.validate (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\definitions\utils.js:128:13)
    at validate (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\validators\validate.js:17:9)
    at builder (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\builders\builder.js:46:27)
    at Object.AssignmentExpression (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\types\lib\builders\generated\index.js:241:31)
    at NodePath.insertAfter (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\traverse\lib\path\modification.js:124:49)
    at C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\helper-module-transforms\lib\rewrite-live-references.js:151:30
    at Array.forEach (<anonymous>)
    at Object.VariableDeclaration (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\helper-module-transforms\lib\rewrite-live-references.js:145:52)
    at NodePath._call (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcelbundler\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\bwilson\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\@babel\traverse\lib\path\context.js:40:17)
`
**Browser (check https://whatismybrowser.com/)** 
 - Browser: Chrome 85 on Windows 10

**What's your OS? (check https://whatsmyos.com):**
 - OS:  Windows 10 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: @arcgis/core 4.17.0-next.20201008

**Comment by odoe** [comment]
Parcel doesn't work at the moment. We're not quite sure why yet, it has to do with how Parcel builds it's local loader.

**Comment by andygup** [comment]
Closing. Parcel is a work-in-progress.
