### ISSUE TITLE
Bug: Read Hydrated Geometry error on LayerView query features

### ISSUE THREAD

**Issue by bbarnell** [Esri/feedback-js-api-next#96]
**Describe the bug**
I am getting the error message below when doing a query on features in a layer view.  The API does not work properly after the first time this error occurs.

stack: "TypeError: Cannot read property 'readHydratedGeometry' of null↵    at Object.getGeometry (https://js.arcgis.com/4.19/esri/views/2d/layers/features/Pipeline.js:531:206)↵    at https://js.arcgis.com/4.19/esri/views/2d/layers/features/Pipeline.js:573:65↵    at https://js.arcgis.com/4.19/esri/views/2d/layers/features/Pipeline.js:573:205↵    at Array.filter (<anonymous>)↵    at H.F._runSpatialFilter (https://js.arcgis.com/4.19/esri/views/2d/layers/features/Pipeline.js:573:195)↵    at H.F._executeGeometryQuery (https://js.arcgis.com/4.19/esri/views/2d/layers/features/Pipeline.js:573:36)"

**To Reproduce**
Run the sample code and then 
[Test_ReadHydratedGeom.txt](https://github.com/Esri/feedback-js-api-next/files/5823109/Test_ReadHydratedGeom.txt)
[Test_ReadHydratedGeom.txt](https://github.com/Esri/feedback-js-api-next/files/5823114/Test_ReadHydratedGeom.txt)

zoom in on the map

**Expected behavior**
Results are returned from the query and no error message

**Browser ** 
Chrome on on Windows 10
 
**What's your OS? (check https://whatsmyos.com):**
 - Device: "Windows 10 desktop PC

**API version (check your console)**
 - Version: ArcGIS API for JavaScript 4.19-next

**Additional context**
The issue does not exist in version 4.16 of the API

**Comment by bbarnell** [comment]
This was a bug in my query geometry.
